Check for required commands and paths before starting

diff --git a/bin/issuegen-netif b/bin/issuegen-netif
--- a/bin/issuegen-netif
+++ b/bin/issuegen-netif
@@ -16,6 +16,18 @@ for arg in "$@"; do [ "${arg}" = "--help" ] || continue
   exit 0
 done
 
+for cmd in find; do
+  if ! command -v "${cmd}" >/dev/null 2>&1; then
+    >&2 printf 'Missing %s, skipping %s\n' "${cmd}" "${0##*/}"
+    exit 0
+  fi
+done
+
+if ! [ -e '/sys/class/net/' ]; then
+  >&2 printf 'Missing /sys/class/net/, (sysfs not mounted?) skipping %s\n' "${0##*/}"
+  exit 0
+fi
+
 case "${1:-}" in
   */*)
     outdir="$1"; shift
diff --git a/bin/issuegen-ssh-host-keys b/bin/issuegen-ssh-host-keys
--- a/bin/issuegen-ssh-host-keys
+++ b/bin/issuegen-ssh-host-keys
@@ -12,6 +12,13 @@ for arg in "$@"; do [ "${arg}" = "--help" ] || continue
   exit 0
 done
 
+for cmd in find ssh-keygen; do
+  if ! command -v "${cmd}" >/dev/null 2>&1; then
+    >&2 printf 'Missing %s, skipping %s\n' "${cmd}" "${0##*/}"
+    exit 0
+  fi
+done
+
 if [ $# -gt 0 ]; then
   outdir="$1"; shift
 fi
